export const siteConfig = {
  title: 'Ahmet Melih Temiz | Full Stack Developer',
  description: "Hello, I'm Ahmet Melih. I am Full Stack Developer from Turkey",
  keywords: [
    'Ahmet Melih Temiz',
    'Ahmet Temiz',
    'Ahmet Melih',
    'Full Stack Developer',
    'Turkey',
    'React',
    'Nest.js',
    'NestJS',
    'Next.js',
    'NextJS',
    'Node.js',
    'NodeJS',
    'Java',
    'Spring Boot',
    'Node',
    'Web development',
    'Software development',
    'Software engineer',
    'Back-end',
    'Front-end',
    'Responsive design',
    'JavaScript',
    'TypeScript',
    'HTML',
    'CSS',
    'Portfolio',
    'Projects',
    'Website',
    'Web applications',
    'Developer',
    'Code',
    'Programming',
    'Coding',
    'Software',
    'Technology',
    'Innovation',
    'OKX API Connect',
    'IDO Launchpad',
    'NFT Marketplace',
    'NetGSM SMS Service',
    'HTML Mail Sender',
    'Exchange Project',
    'Balance Network Exchange',
    'Order Matching Engine',
    'Customer Info Design',
    'Modal Design',
    'Tailwind CSS',
    'Docker',
    'MongoDB',
    'Redis',
    'PostgreSQL',
    'Ethers',
    'Monorepo',
    'Microservices',
    'REST API',
    'WebSockets',
  ],
  url: process.env.SITE_URL || 'https://example.com',
  googleSiteVerificationId: process.env.GOOGLE_SITE_VERIFICATION_ID || '',
};
