export const siteConfig = {
  title: 'Ahmet Melih Temiz | Full Stack Developer',
  description: "Hello, I'm Ahmet Melih. I am Full Stack Developer from Turkey",
  keywords: [
    'Ahmet Melih Temiz',
    'Full Stack Developer',
    'Turkey',
    'React',
    'Nest.js',
    'Java',
    'Node.js',
    'Web development',
    'Software development',
    'Software engineer',
    'Back-end',
    'Front-end',
    'UI/UX',
    'Responsive design',
    'JavaScript',
    'TypeScript',
    'HTML',
    'CSS',
    'Portfolio',
    'Projects',
    'Website',
    'Web applications',
    'Developer',
    'Code',
    'Programming',
    'Coding',
    'Software',
    'Technology',
    'Innovation',
  ],
  url: process.env.SITE_URL || 'https://example.com',
  googleSiteVerificationId: process.env.GOOGLE_SITE_VERIFICATION_ID || '',
};
